package com.company;
import java.awt.*;
import javax.swing.*;
import java.awt.Panel;
import javax.swing.JPanel;

/**
 * Created by Moishe on 15/06/2017.
 */
public class App extends JFrame {

    public static void main(String[] args) {
        new App();
    }

    public App() {
        this.setSize(400, 400);
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        Toolkit tk = Toolkit.getDefaultToolkit();

        Dimension dim = tk.getScreenSize();

        int xPos = (dim.width / 2) - (this.getWidth() / 2);
        int yPos = (dim.height / 2) - (this.getHeight() / 2);

        this.setResizable(false);

        this.setLocation(xPos, yPos);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("The App");

        //create a panel
        JPanel thePanel = new JPanel();
        JLabel Label_title = new JLabel("Picture Builder");
        thePanel.add(Label_title);
        this.add(thePanel);

        //buttom shadow test
        JButton Buttom_shadow_test = new JButton("Shadow /n Test");
        Buttom_shadow_test.setBorderPainted(true);
        Buttom_shadow_test.setText("Shadow Test");
        Buttom_shadow_test.setToolTipText("press here to initialize the shadow text");
        thePanel.add(Buttom_shadow_test);

        //text field
        JTextField direction_light = new JTextField("hi", 15);
        direction_light.setColumns(10);
        direction_light.setText("hi s");
        direction_light.setToolTipText("ii is a filed");
        thePanel.add(direction_light);

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
